universe = vanilla
executable = condor/run_condor.sh
Output = condor/condorOut/condor.$ENV(OUT).stdout
Error = condor/condorOut/condor.$ENV(OUT).stderr
Log = condor/condorOut/condor.$ENV(OUT).log
Arguments = $ENV(IN) $ENV(OUT) $ENV(TPCNTUPLE_DIR) $ENV(DELPHINANOAOD_DIR) $ENV(ISMC)
should_transfer_files = Yes
+JobFlavour  = "espresso"
RequestCpus = 4
x509userproxy = $ENV(X509_USER_PROXY)
use_x509userproxy = True
getenv= True
queue 1